import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import getProducts from '../utils/commerce'

export default function Home({ products }) {

  console.log(products)
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        {products.map((product) => {
          return (
            <div key={product.id}>
              <img src={product.media.source} alt={product.name} />
              <p>{product.name}</p>
              <p>{product.price.formatted_with_symbol}</p>
            </div>
          )
        })}
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const commerce = getProducts();
  const { data: products } = await commerce.products.list()
  return {
    props: {
      products
    }
  }
}
