import { Link } from '@material-ui/core'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import getProducts from '../utils/commerce'

export default function Home({ products }) {

  console.log(products)
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid grid-cols-4 mx-auto py-10 w-full">
        {products.map((product) => {
          return (
            <div key={product.id} className="mx-auto cursor-pointer w-50 h-70 shadow-md border-blue-200">
              <div >
                <Link href={`products/${product.id}`}>
                  <img src={product.media.source} alt={product.name} className="w-40 h-50 cursor-pointer" />
                </Link>

                <p>{product.name}</p>
                <p>{product.price.formatted_with_symbol}</p>
              </div>

            </div>
          )
        })}
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const commerce = getProducts();
  const { data: products } = await commerce.products.list()
  return {
    props: {
      products
    }
  }
}
