import { blogPost } from '../../utils/data'
import Head from 'next/head'

export async function getStaticProps(context) {
    const { params } = context
    return {
        props: blogPost.find((blog) => blog.slug === params.slug)
    }
}

export async function getStaticPaths() {

    return {
        paths: blogPost.map((blog) => ({
            params: {
                slug: blog.slug
            }
        })),
        fallback: false
    }
}


const DetailPage = ({ title, date, content }) => {
    return (
        <div >
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main >
                <h1>{title}</h1>
                <div>{content}</div>
            </main>

        </div>
    )
}

export default DetailPage
