import Head from 'next/head'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Home-FB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main >
        <h1>Facebook Clone</h1>
      </main>
    </div>
  )
}
