import Head from 'next/head'
import Navbar from '../components/Navbar'
import { getSession, useSession, signIn, signOut } from 'next-auth/client'
import LoginPage from '../components/LoginPage'
import Sidebar from '../components/Sidebar'
import Feeds from '../components/Feeds'

export default function Home({ session }) {
  // const [session] = useSession()

  // !session && <LoginPage />
  if (!session) return <LoginPage />
  console.log(session)

  return (
    <div >
      <Head>
        <title>Home-FB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="flex" >
        <Sidebar />
        <Feeds />
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  return {
    props: {
      session
    }
  }
}