import Head from 'next/head'
import { blogPost } from '../utils/data'
import Link from 'next/link'

export default function Home() {

  return (
    <div >
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1>MDX BLOG</h1>
      </main>

      <div>
        {blogPost.map((blog) => {
          return (
            <div key={blog.slug}>
              <div>
                <Link href={`/blog/${blog.slug}`} >{blog.title}</Link>
              </div>
              <div>{blog.date.toString()}</div>
              <div>{blog.content}</div>
            </div>
          )
        })}
      </div>

    </div>
  )
}
