import Head from "next/head";
const Home = () => {
  return (
    <div>
      <Head>
        <title>Next Crash Course</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>This is Home Page</h1>
    </div>
  );
};

export default Home;
